package com.kweather.domain.senta.dto

data class SenTaIndexItem(
    val code: String?,
    val areaNo: String?,
    val date: String?,
    val h1: String?,
    val h2: String?,
    val h3: String?,
    val h4: String?,
    val h5: String?,
    val h6: String?,
    val h7: String?,
    val h8: String?,
    val h9: String?,
    val h10: String?,
    val h11: String?,
    val h12: String?,
    val h13: String?,
    val h14: String?,
    val h15: String?,
    val h16: String?,
    val h17: String?,
    val h18: String?,
    val h19: String?,
    val h20: String?,
    val h21: String?,
    val h22: String?,
    val h23: String?,
    val h24: String?,
    val h25: String?,
    val h26: String?,
    val h27: String?,
    val h28: String?,
    val h29: String?,
    val h30: String?,
    val h31: String?
)